name: "Deploy to GH pages"

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.openscad-deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          path: main
      - name: Checkout customizer
        uses: actions/checkout@v5
        with:
          repository: Bob-vdV/openscad-gh-pages
      - name: Copy main files to root
        run: cp -a main/. ./
        shell: bash
      - name: list files
        run: ls -R ./
        shell: bash
      - name: Deploy openscad customizer
        uses: ./
        id: openscad-deployment
        with:
          filename: "centercap_main.scad"
          libraries: "deploy/libraries.json"
